### PR TITLE
Changed fridge to use brazier like interface

### PR DESCRIPTION
**Pull request by SqFKYo**
Closes issue https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/9 by making fridge deconstruct brazier like via [e]xamine menu.

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
You need to add 

`    "use_action": { "type": "deploy_furn", "furn_type": "f_fridge" }`

`to the fridge item to allow the player to make the fridge furniture again.

**Comment by Noctifer-de-Mortem** [comment]
Looks good. Gonna test it in a bit and if everything is in working then a merge is in order.

**Comment by BorkBorkGoesTheCode** [comment]
How've you been @Noctifer-de-Mortem ? I haven't seen you much on discourse.

**Comment by Noctifer-de-Mortem** [comment]
@BorkBorkGoesTheCode Haven't checked the forums at all for quite some time. It's difficult to navigate and I've been out of the Cata community in general it seems. Still check the github every once in a while and am trying to add stuff to this mod.

**Pull request merged**
