### PR TITLE
Add zh_CN translation

### PR DESCRIPTION
**Pull request by HuajiSama**
Add zh_CN translation
Update nocts_cata_mod_DDA.pot
增加中文翻译
更新.pot文件

### CODE REVIEW

**Comment by chaosvolt** [comment]
Question now that I've been asked about this on the discord, how does one enable mod translations in DDA? I don't see any sign of the feature having been ported over from BN yet, but still trying to find it.

**Comment by HuajiSama** [comment]
DDA/doc/TRANSLATING_MOD.md

**Comment by chaosvolt** [comment]
Found it, yeah. So it looks like it should be automatically applied in a localized release if available, weird. Not sure why but evidently it wasn't for them. :/

**Comment by HuajiSama** [comment]
image

**Comment by chaosvolt** [comment]
Oh, that's weird. They'd have to compile it themselves to use mod translations?

**Comment by HuajiSama** [comment]
Cataclysm-DDA>python3 ./lang/extract_json_strings.py -i ./mods/nocts_cata_mod_DDA -o ./mods/nocts_cata_mod_DDA/lang/po/nocts_cata_mod_DDA.pot

**Comment by HuajiSama** [comment]
Documents\GitHub\Cataclysm-DDA>python3 ./lang/extract_json_strings.py -i ./mods/nocts_cata_mod_DDA -o ./mods/nocts_cata_mod_DDA/lang/po/nocts_cata_mod_DDA.pot

**Comment by chaosvolt** [comment]
Hmm. Not sure what they might've missed, not really experienced with making use of mod translations. ^^"

**Pull request merged**
