### PR TITLE
Removed some redundant and obsolete data; updated modinfo

### PR DESCRIPTION
**Pull request by BorkBorkGoesTheCode**
This won't fix 10 but it will futureproof the mod somewhat. 
Replaced most instances of "override" in c_ranged with copy-from and removed all coregame data unmodified by override; updated the name of the cheap laser pistol; added the new "emitter" and "lens" modslots to the coregame guns where present; moved overrides to c_ranged_override.json; updated the modinfo.json

### CODE REVIEW

**Comment by chaosvolt** [comment]
> this won't fix

Small problem, github parses that statement as "fix 10" meaning merging this will still close it.

Will test the branch in a bit when I can get back on.

**Comment by BorkBorkGoesTheCode** [comment]
@chaosvolt how's Noctifer doing?

**Comment by chaosvolt** [comment]
Been the usual from what they've said, not as active on github otherwise. Usually I end up poking them on discord about PRs on here. Speaking of, now to test then link them to it.

**Comment by chaosvolt** [comment]
Seems to be all good, no load errors and overrides seem to be set up as intended. Guess can merge it, might lint up the new file afterward.

**Pull request merged**
