### PR TITLE
Buff Apophis into a true challange.

### PR DESCRIPTION
**Pull request by Noctifer-de-Mortem**
Added the 'PRIORITIZE_TARGETS' flag and buffed his stats to an "appropriate" amount. Not much else to say; it is a simple change but an effective one. Should make him Car-Fu, resistant if not immune,

### CODE REVIEW

**Comment by chaosvolt** [comment]
> ten thousand HP, up to 110 damage per hit, all armor at 50

That's...pretty damn strong, yeah.

**Comment by chaosvolt** [comment]
Doing a bit of testing so far. Evy's laser rifle won't scratch it, nor will Alpha with every CBM available thrown into the fight. Laser LMG works a bit but it's a massive amount of health to chew through. Laser sniper can't burn through all that HP fast enough either. Reload time for the ionic cannon means it'll be at full health before you can make a follow-up shot.

You are correct that it's now car-fu-proof, but seeing as it now spawns underground in a confined lab, under a complex with multiple buildings, fences, and trees...

**Comment by Noctifer-de-Mortem** [comment]
Then it's buffed appropriately. The whole car-fu was a joke mostly. Just straight up killing in it in a fire-fight shouldn't be the go to strategy here, people should find creative ways to kills it rather than "fire the biggest gun I have!"

**Comment by chaosvolt** [comment]
...I don't think there legit IS a way to kill it, the way you set this up. Every weapon in the game will either do nothing or be so slow that he'll regen to full health before you can get another shot off. There's no debuff or environmental that'll do enough damage over time that counter 50 HP per turn regen, telefragging will only, if I recall, do either a fifth or half of that HP, EMPs don't affect it, monster infighting won't affect it in the slightest due to regen, etc.

I legit can't think of any tactic, no matter how creative, short of using a 120mm tank cannon (which is not vanilla) that'll kill it, period.

**Comment by Noctifer-de-Mortem** [comment]
1. Kills all monsters
2.Use lots of explosives to wear it down.
3. Use NPCs to unload a lot of firepower.

Let me run some tests too

**Comment by Noctifer-de-Mortem** [comment]
Took a while but manage to do it. Had to kill all other monsters, corner it and then three LAWs fired at it in a row. Very difficult but doable.

**Pull request merged**
